# Generated by Django 4.2.5 on 2023-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtoservico', '0001_initial'),
        ('produto', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(through='produtoservico.ProdutoServico', to='produto.produto'),
        ),
    ]
