# Generated by Django 4.2.5 on 2023-10-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='endereco',
            new_name='funcao',
        ),
    ]
